.TH "D:/Temp/PI/AulasPI/Aula 6 -Arrays/Aula.c" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/PI/AulasPI/Aula 6 -Arrays/Aula.c \- Manipulação de Arrays Simples e Strings Strings == array de caracteres terminado com '\\0' Tipos de Dados estruturados\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'Header\&.h'\fP
.br
\fC#include <locale\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manipulação de Arrays Simples e Strings Strings == array de caracteres terminado com '\\0' Tipos de Dados estruturados\&. 


.PP
\fBAuthor\fP
.RS 4
lufer 
.RE
.PP
\fBDate\fP
.RS 4
2022 
.RE
.PP

.PP
Definition in file \fBAula\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line \fB15\fP of file \fBAula\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aulas de PI - EIM from the source code\&.
