.TH "D:/Temp/PI/AulasPI/Aula 6 -Arrays Directory Reference" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/PI/AulasPI/Aula 6 -Arrays Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAula\&.c\fP"
.br
.RI "Manipulação de Arrays Simples e Strings Strings == array de caracteres terminado com '\\0' Tipos de Dados estruturados\&. "
.ti -1c
.RI "file \fBFuncoes\&.c\fP"
.br
.RI "Funções para manipular arrays Manipular strings como array de char\&. "
.ti -1c
.RI "file \fBHeader\&.h\fP"
.br
.RI "Assinaturas de funções e Tipos de Dados Structs\&. "
.ti -1c
.RI "file \fBNovo\&.c\fP"
.br
.ti -1c
.RI "file \fBSource\&.c\fP"
.br
.ti -1c
.RI "file \fBStrings\&.c\fP"
.br
.RI "Funções que manipulam strings\&. "
.ti -1c
.RI "file \fBTeste\&.c\fP"
.br
.RI "
.br
 "
.in -1c
