.TH "pessoa" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pessoa
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBnome\fP [\fBMAXNOME\fP]"
.br
.ti -1c
.RI "int \fBidade\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBHeader\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int idade"

.PP
Definition at line \fB20\fP of file \fBHeader\&.h\fP\&.
.SS "char nome[\fBMAXNOME\fP]"

.PP
Definition at line \fB19\fP of file \fBHeader\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aulas de PI - EIM from the source code\&.
