.TH "D:/Temp/PI/AulasPI/Aula 6 -Arrays/Source.c" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/PI/AulasPI/Aula 6 -Arrays/Source.c
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Aulas de PI - EIM from the source code\&.
