.TH "D:/Temp/PI/AulasPI/Aula 6 -Arrays/Strings.c" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/PI/AulasPI/Aula 6 -Arrays/Strings.c \- Funções que manipulam strings\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinicializaArray\fP (char n[], int size, char ch)"
.br
.ti -1c
.RI "int \fBondeEstaChar\fP (char v[], int size, char ch)"
.br
.ti -1c
.RI "\fBboolean\fP \fBexisteChar\fP (const char v1[], char ch)"
.br
.ti -1c
.RI "\fBboolean\fP \fBexisteCharI\fP (char v[], int size, char ch)"
.br
.ti -1c
.RI "char * \fBallChar\fP (const char v1[], char ch)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Funções que manipulam strings\&. 


.PP
\fBAuthor\fP
.RS 4
lufer 
.RE
.PP
\fBDate\fP
.RS 4
2022 
.RE
.PP

.PP
Definition in file \fBStrings\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "char * allChar (const char v1[], char ch)"
Devolve todos os caracteres existentes num array de caracteres\&.
.PP
\fBParameters\fP
.RS 4
\fIv1\fP 
.br
\fIch\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBStrings\&.c\fP\&.
.SS "\fBboolean\fP existeChar (const char v1[], char ch)"

.PP
Definition at line \fB43\fP of file \fBStrings\&.c\fP\&.
.SS "\fBboolean\fP existeCharI (char v[], int size, char ch)"
Verifica se determinado caracter existe num array de caracteres\&.
.PP
\fBParameters\fP
.RS 4
\fIv\fP 
.br
\fIsize\fP 
.br
\fIch\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBStrings\&.c\fP\&.
.SS "void inicializaArray (char n[], int size, char ch)"
Inicializa um array com determinado caracter\&.
.PP
\fBParameters\fP
.RS 4
\fIn\fP 
.br
\fIsize\fP 
.br
\fIch\fP 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBStrings\&.c\fP\&.
.SS "int ondeEstaChar (char v[], int size, char ch)"
Indica a posição onde se encontra determinado caracter num array de caracteres\&.
.PP
\fBParameters\fP
.RS 4
\fIv\fP 
.br
\fIsize\fP 
.br
\fIch\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBStrings\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aulas de PI - EIM from the source code\&.
