.TH "D:/Temp/PI/AulasPI/Aula 6 -Arrays/Teste.c" 3 "Fri Oct 28 2022" "Version 1.0" "Aulas de PI - EIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/PI/AulasPI/Aula 6 -Arrays/Teste.c \- 
.br
  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSoma\fP (int x, int y)"
.br
.RI "Calcula a soma de dois valores inteiros\&. "
.in -1c
.SH "Detailed Description"
.PP 

.br
 


.PP
\fBAuthor\fP
.RS 4
lufer 
.RE
.PP
\fBDate\fP
.RS 4
October 2022 
.RE
.PP

.PP
Definition in file \fBTeste\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int Soma (int x, int y)"

.PP
Calcula a soma de dois valores inteiros\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Valor de entrada 
.br
\fIy\fP Valore de entrada 
.RE
.PP
\fBReturns\fP
.RS 4
Soma dos dois dalores 
.RE
.PP
\fBAuthor\fP
.RS 4
lufer 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBTeste\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aulas de PI - EIM from the source code\&.
